### ISSUE TITLE
Compilation error: ‘class QList<EffectPlugin*>’ has no member named ‘swapItemsAt’

### ISSUE THREAD

**Issue by gitnob** [wahjam/wahjam#156]
Can not compile the code because of missing member function and definition.
Called in line 137 and 148 of EffectProcessor.cpp.
This is due to introducing this member function only from QList version 5.13 on.

Just replace with preprocessor code:

#if QT_VERSION < QT_VERSION_CHECK(5,13,0)
  plugins.swap(idx, idx + 1);
#else
  plugins.swapItemsAt(idx, idx + 1);
#endif 

and you should to be good to go (at least with my version of qt)

**Comment by wahjam** [comment]
On Mon, Aug 10, 2020 at 9:55 AM gitnob <notifications@github.com> wrote:

> Can not compile the code because of missing member function and definition.
> Called in line 137 and 148 of EffectProcessor.cpp.
>
QList::swapItemsAt() was introduced in Qt 5.13. Are you trying to build
with an old version of Qt?

https://doc.qt.io/qt-5/qlist.html#swapItemsAt

**Comment by gitnob** [comment]
I did compile with an older qt version (5.11 on Debian stable). Without the above lines of code, no problems until now. But have to test against a jamming session this evening - it's quite quiet now :(
