### ISSUE TITLE
curses.h

### ISSUE THREAD

**Issue by goldenfool** [wahjam/wahjam#5]
hello, 

  wow i like this project!

just another compiling issue:

trying to compile on   ubuntu 11.10 oneiric ocelot     with  make 
error occurs:  
...
cursesclient.cpp:35:20: fatal error: curses.h: No such file or directory
compilation terminated.
make: **\* [cursesclient.o] Error 1

taking a look in cursesclient.cpp there i see #include curses.h  
but curses.h doesnt exist anywhere, cant find it

im doing wrong?  why this include file if it doesn't exist?
in ninjam its exactly the same ... 

EDIT:  found it, for everyone having same problem: google ...  http://ubuntuforums.org/showthread.php?t=321810

now make made everything but i cant find the resulting file

EDIT:    all problems appeared cause im a newbi to ubuntu   sorry     ok i got ninjam running    thank you
